In [1]:
import os
import joblib 
import pandas as pd
import numpy as np
import custom.deploy_models as dp

In [2]:
XGboost_mod1_PATH = os.path.join("data", 
                                 "5_deployment", 
                                  "XGboost_mod1.joblib")
    
with open(XGboost_mod1_PATH, 'rb') as f:
    XGboost_mod1 = joblib.load(f)
    
txt = np.array(["I'm stocked. I'm alive. I am..."])

In [3]:
try:
    (
    X_test_counter
    , X_test_bot
    , X_train_transformer_vocab
    , X_test_tfidf
    , X_test_svd
    , test_mean_spam_sims
    , X_test_processed
    ) = dp.transform_newdata(txt)
    
    y_pred = XGboost_mod1.predict(X_test_processed)
except Exception as e:
    raise e

In [19]:
prediction = y_pred[0]
counter = dict(X_test_counter[0])
bot = X_test_bot.toarray()
tfidf = X_test_tfidf.todense()
svd = X_test_svd
X = X_test_processed.todense()

In [20]:
counter

{'i': 3,
 'am': 3,
 'stocked': 1,
 'alive': 1,
 'i_am': 3,
 'am_stocked': 1,
 'stocked_i': 1,
 'am_alive': 1,
 'alive_i': 1,
 'i_am_stocked': 1,
 'am_stocked_i': 1,
 'stocked_i_am': 1,
 'i_am_alive': 1,
 'am_alive_i': 1,
 'alive_i_am': 1}

In [21]:
vocabulary = list(X_train_transformer_vocab)[:20]

In [28]:
bot

array([[12,  0,  3, ...,  0,  0,  0]], dtype=int32)

In [33]:
df = pd.DataFrame()
df['train vocab >>>'] = vocabulary
df['new tokens'] = bot[:,1:21][0]
df.set_index('train vocab >>>', inplace=True)
df.T

train vocab >>>  NUM  i  you  u  me  my  not  have  your  call  am  EMOJI  do  \
new tokens         0  3    0  0   0   0    0     0     0     0   3      0   0   

train vocab >>>  i_am  now  NUM_NUM  so  but  or  we  
new tokens          3    0        0   0    0   0   0

In [37]:
tfidf

matrix([[0.31310347, 0.        , 0.36829362, ..., 0.        , 0.        ,
         0.        ]])

In [40]:
svd[0][:10]

array([ 0.02036149, -0.03459074,  0.08198418,  0.01807301, -0.06391494,
        0.01263903, -0.03529285, -0.01488637,  0.02711607,  0.01858909])