In [2]:
import os
import joblib 
import pandas as pd
import numpy as np
import custom.deploy_models as dp

In [3]:
XGboost_mod1_PATH = os.path.join("data", 
                                 "5_deployment", 
                                  "XGboost_mod1.joblib")
    
with open(XGboost_mod1_PATH, 'rb') as f:
    XGboost_mod1 = joblib.load(f)
    
txt = np.array(["I'm stocked. I'm alive. I am..."])

In [4]:
try:
    (
    counter
    , vocabulary
    , bot
    , X_test_tfidf
    , X_test_svd
    , test_mean_spam_sims
    , X_test_processed
    ) = dp.transform_newdata(txt)
    
    y_pred = XGboost_mod1.predict(X_test_processed)
except Exception as e:
    raise e

In [5]:
prediction = y_pred[0]
prediction

0

In [9]:
print(counter)

{'i': 3, 'am': 3, 'stocked': 1, 'alive': 1, 'i_am': 3, 'am_stocked': 1, 'stocked_i': 1, 'am_alive': 1, 'alive_i': 1, 'i_am_stocked': 1, 'am_stocked_i': 1, 'stocked_i_am': 1, 'i_am_alive': 1, 'am_alive_i': 1, 'alive_i_am': 1}


In [8]:
print(vocabulary)

['NUM', 'i', 'you', 'u', 'me', 'my', 'not', 'have', 'your', 'call', 'am', 'EMOJI', 'do', 'i_am', 'now', 'NUM_NUM', 'so', 'but', 'or', 'we', 'can', 'get', 'if', 'ur', 'no', 'just', 'this', 'EMOJI_NUM', 'go', 'up', 'how', 'when', 'ok', 'what', 'free', 'i_will', 'day', 'out', 'all', 'know', 'come', 'like']


In [10]:
print(bot)

[0 3 0 0 0 0 0 0 0 0 3 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0]


In [18]:
tfidf = X_test_tfidf.toarray()[:,1:43][0]

In [19]:
tfidf

array([0.        , 0.36829362, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.60404763, 0.        , 0.        , 0.63360279, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ])

In [33]:
df = pd.DataFrame()
df['train vocab >>>'] = vocabulary
df['new tokens'] = bot[:,1:21][0]
df.set_index('train vocab >>>', inplace=True)
df.T

train vocab >>>  NUM  i  you  u  me  my  not  have  your  call  am  EMOJI  do  \
new tokens         0  3    0  0   0   0    0     0     0     0   3      0   0   

train vocab >>>  i_am  now  NUM_NUM  so  but  or  we  
new tokens          3    0        0   0    0   0   0

In [37]:
tfidf

matrix([[0.31310347, 0.        , 0.36829362, ..., 0.        , 0.        ,
         0.        ]])

In [40]:
svd[0][:10]

array([ 0.02036149, -0.03459074,  0.08198418,  0.01807301, -0.06391494,
        0.01263903, -0.03529285, -0.01488637,  0.02711607,  0.01858909])